### ISSUE TITLE
Google Login

### ISSUE THREAD

**Issue by sun-415** [sun-415/CSE-110-Project#5]
- The app includes a "Sign in with Google" button that allows users to log in using their Google account.
- Google authentication is set up to securely handle user login and retrieve basic account information.
- Upon successful login, the user is assigned a unique account ID that is used to save and retrieve their data in the backend.
- If the login is unsuccessful, the user sees an appropriate error message without access to the app.
- The user remains logged in across sessions, with an option to log out if feasible.

**Comment by eholguin1** [comment]
"Sign in with Google" button works for user to login in with their google account expect button is in the wrong location which still needs to get fixed. It keeps the user login in while going their different sections but logins them out when the application is existed. 
An unsuccessful login would not usually happen as they are login in with google as an error message is not really needed. 
On Home page, after signing in a "Welcome (their name)" will pop up to show unique for each user.

**Comment by sun-415** [comment]
Update: in the process of moving the login button to the correct location.
